# Deep Survival Machines task configuration

defaults:
  - losses: dsm
  - metrics: default

eval_metric: "eval_ipcw_avg"
eval_metric_greater_is_better: true

config:
  _target_: sat.models.heads.MTLConfig
  _convert_: "partial"
  freeze_transformer: false
  initializer_range: ${mtl_initializer_range}
  initializer: ${mtl_initializer}
  pretrained_params: ${transformers}
  sentence_emb: ${sentence_emb}
  token_emb: ${token_emb}
  hidden_size: ${transformer_hidden_size}
  num_features: ${tokenizers.max_seq_length}
  intermediate_size: ${shared_intermediate_size}
  num_labels: ${shared_num_labels}
  batch_norm: ${shared_batch_norm}
  hidden_dropout_prob: ${shared_hidden_dropout_prob}
  bias: ${shared_bias}
  num_hidden_layers: ${shared_num_hidden_layers}
  select_hidden_layers: ${select_hidden_layers}
  return_dict: true
  task_heads:
    - _target_: sat.models.heads.DSMConfig
      _recursive_: false
      initializer_range: ${survival_initializer_range}
      initializer: ${survival_initializer}
      num_features: ${shared_num_labels}
      intermediate_size: ${survival_shared_intermediate_size}
      num_hidden_layers: ${survival_shared_num_hidden_layers}
      indiv_intermediate_size: ${dsm_intermediate_size}
      indiv_num_hidden_layers: ${dsm_num_hidden_layers}
      num_labels: ${data.label_transform.cuts}
      batch_norm: ${dsm_batch_norm}
      hidden_dropout_prob: ${dsm_hidden_dropout_prob}
      bias: ${dsm_bias}
      loss: ${tasks.losses}
      loss_weight: ${survival_loss_weight}
      num_events: ${data.num_events}
      num_mixtures: ${dsm_num_mixtures}
      distribution: ${dsm_distribution}
      temp: ${dsm_temp}
      discount: ${dsm_discount}
