[tool.poetry]
name = "sat"
version = "1.1.7.3"
description = "Survival Analysis using Transformers"
authors = [
    "Dominik Dahlem <mail@dominik-dahlem.com>",
]
maintainers = [
    "Dominik Dahlem <mail@dominik-dahlem.com>",
    "Mahed Abroshan <mahed.ab@gmail.com>",
]
readme = "README.md"
repository = "https://github.com/sat/sat.git"
keywords = ["survival", "transformer"]

[tool.poetry.dependencies]
python = ">=2.1,>=3.9,<3.13"
hydra-core = "^1.3.2"
hydra-colorlog = "^1.2.0"
transformers = {extras = ["torch"], version = "==4.39.3"}
datasets = "^2.18"
evaluate = "^0.4.1"
h5py = "^3.8.0"
pandas = "^2.2.2"
tables = "^3.9.2"
scikit-learn = "^1.3.2"
logdecorator = "^2.4"
nvidia-ml-py3 = "^7.352.0"
tensorboard = "^2.16.2"
bootstrap-stat = "^0.2.4.2"
tokenizers = "^0.15"
numba = "^0.59.0"
numpy = "^1.26.2"
einops = "^0.7.0"
lifelines = "^0.27.8"
torchtuples = "^0.2.2"
mlflow = "^2.12.1"

[tool.poetry.dev-dependencies]

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"
coverage = "^7.3.2"

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "DEBUG"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
