# @package _global_
hydra:
  sweeper:
    direction: [maximize, minimize]
    n_jobs: 1
    n_trials: 50
    params:
      learning_rate: tag(log, interval(1e-5, 1e-2))
      weight_decay: tag(log, interval(1e-5, 1e-1))
      transformer_hidden_size: choice(8, 16, 32)
      transformer_intermediate_size: choice(32, 64, 96)
      transformer_num_attention_heads: choice(2, 4)
      transformer_num_hidden_layers: choice(1, 2, 4)
      survival_intermediate_size: choice(8, 16, 24)
      token_emb: choice(2, 3, 4, 5)
      sentence_emb: choice(1, 2, 3)
    sampler:
      _target_: optuna.samplers.NSGAIISampler
      population_size: 20
      mutation_prob: null
      crossover_prob: 0.9
      swapping_prob: 0.5
      constraints_func: null
      seed: ${seed}
    storage: sqlite:///${modelhub}/${dataset}/${modelname}/studies.db
    study_name: ${dataset}_${modelname}
optuna:
  metric: [test_ipcw_avg, test_brier_avg]
  metric_direction: [maximize, minimize]
  pruner:
    _target_: optuna.pruners.MedianPruner
    interval_steps: 5
    n_startup_trials: 5
    n_warmup_steps: 20
  study_overwrite: true
