# This file defines the parameter search space for Optuna
# @package _global_
hydra:
  sweeper:
    sampler:
      seed: ${seed}
      consider_prior: true
      prior_weight: 1.0
      consider_magic_clip: true
      consider_endpoints: false
      n_startup_trials: 10
      n_ei_candidates: 24
      multivariate: false
      warn_independent_sampling: true

      direction: ${optuna.metric}
      storage: sqlite:///${modelhub}/${dataset}/${modelname}/studies.db
      study_name: ${dataset}_${modelname}
      n_trials: 50
      n_jobs: 1
      max_failure_rate: 0.0

    # Define parameter search spaces
    params:
      # Model architecture parameters
      # Training parameters
      learning_rate:
        type: float
        low: 1e-5
        high: 1e-2
        log: true

      weight_decay:
        type: float
        low: 1e-5
        high: 1e-1
        log: true

      transformer_hidden_size:
        type: categorical
        choices: [8, 16, 32]

      transformer_intermediate_size:
        type: categorical
        choices: [32, 64, 96]

      transformer_num_attention_heads:
        type: categorical
        choices: [2, 4]

      transformer_num_hidden_layers:
        type: categorical
        choices: [1, 2, 4]

      survival_intermediate_size:
        type: categorical
        choices: [8, 16, 24]

      token_emb:
        type: categorical
        choices: [2, 3, 4, 5]

      sentence_emb:
        type: categorical
        choices: [1, 2, 3]

# Custom settings for pruning
optuna:
  study_overwrite: true  # Set to false to resume existing study
  # Metric to optimize
  metric: test_ipcw_avg
  metric_direction: "maximize"  # "maximize" or "minimize"
  
  # Pruner selection
  # Options: median, percentile, threshold, hyperband, successive_halving, patient, nop
  pruner:
    _target_: optuna.pruners.MedianPruner
    n_startup_trials: 5  # Number of trials to run before pruning starts
    n_warmup_steps: 20   # Number of steps per trial before pruning is enabled
    interval_steps: 5    # Interval between pruning checks
    
  # Pruning configuration options for different pruners:
  # For MedianPruner:
  #   n_startup_trials: 5
  #   n_warmup_steps: 20
  #   interval_steps: 5
  #
  # For PercentilePruner:
  #   percentile: 25
  #   n_startup_trials: 5
  #   n_warmup_steps: 20
  #   interval_steps: 5
  #
  # For ThresholdPruner:
  #   lower: 0.0
  #   upper: 1.0
  #   n_warmup_steps: 20
  #   interval_steps: 5
  #
  # For HyperbandPruner:
  #   min_resource: 1
  #   max_resource: 100
  #   reduction_factor: 3
  #
  # For SuccessiveHalvingPruner:
  #   min_resource: 1
  #   reduction_factor: 4
  #   min_early_stopping_rate: 0
  #
  # For PatientPruner:
  #   surrogate_pruner:
  #     _target_: optuna.pruners.MedianPruner
  #     n_startup_trials: 5
  #     n_warmup_steps: 0
  #     interval_steps: 1
  #   patience: 5
  #
  # For NopPruner: {}
