# @package _global_

do_sweep: true
job: sweep

defaults:
  - override /callbacks: azureml

hydra:
  launcher:
    job:
      params:
        learning_rate: 0.1
        warmup_steps: 40
        weight_decay: 0
        token_emb: 2
        sentence_emb: 2
        dropout: 0.0
        transformer_hidden_size: 8
        transformer_num_hidden_layers: 2
        transformer_num_attention_heads: 1
        transformer_intermediate_size: 32
        shared_intermediate_size: 64
        shared_batch_norm: true
        shared_bias: true
        shared_num_hidden_layers: 1
        shared_num_labels: 2
        survival_intermediate_size: 64
        survival_batch_norm: true
        survival_bias: true
        survival_num_hidden_layers: 0
        regression_intermediate_size: 64
        regression_batch_norm: true
        regression_bias: true
        regression_num_hidden_layers: 0
        regression_loss_weight: 1.0
      sweep:
        primary_metric: "eval_ipcw"
        goal: "maximize"
        params:
          learning_rate:
            _target_: azure.ai.ml.sweep.Choice
            values:
              - 0.1
              - 0.01
              - 0.001
              - 0.0001
              - 0.00001
          warmup_steps:
            _target_: azure.ai.ml.sweep.Choice
            values:
              - 20
              - 40
              - 80
          weight_decay:
            _target_: azure.ai.ml.sweep.Choice
            values:
              - 0.3
              - 0.1
              - 0.01
              - 0.001
              - 0.0001
              - 0.00001
          token_emb:
            _target_: azure.ai.ml.sweep.Choice
            values:
              - 2
              - 3
              - 4
              - 5
          sentence_emb:
            _target_: azure.ai.ml.sweep.Choice
            values:
              - 2
              - 3
          dropout:
            _target_: azure.ai.ml.sweep.Choice
            values:
              - 0.0
              - 0.05
              - 0.1
              - 0.15
              - 0.2
              - 0.25
          transformer_hidden_size:
            _target_: azure.ai.ml.sweep.Choice
            values:
              - 4
              - 8
              - 16
          transformer_num_attention_heads:
            _target_: azure.ai.ml.sweep.Choice
            values:
              - 1
              - 2
              - 4
          transformer_intermediate_size:
            _target_: azure.ai.ml.sweep.Choice
            values:
              - 16
              - 32
              - 64
          transformer_num_hidden_layers:
            _target_: azure.ai.ml.sweep.Choice
            values:
              - 1
              - 2
              - 3
          shared_intermediate_size:
            _target_: azure.ai.ml.sweep.Choice
            values:
              - 16
              - 32
              - 64
              - 128
          shared_batch_norm:
            _target_: azure.ai.ml.sweep.Choice
            values:
              - 1
              - 0
          shared_bias:
            _target_: azure.ai.ml.sweep.Choice
            values:
              - 1
              - 0
          shared_num_hidden_layers:
            _target_: azure.ai.ml.sweep.Choice
            values:
              - 1
              - 2
              - 3
          shared_num_labels:
            _target_: azure.ai.ml.sweep.Choice
            values:
              - 2
              - 4
              - 8
              - 16
          survival_intermediate_size:
            _target_: azure.ai.ml.sweep.Choice
            values:
              - 16
              - 32
              - 64
              - 128
          survival_batch_norm:
            _target_: azure.ai.ml.sweep.Choice
            values:
              - 1
              - 0
          survival_bias:
            _target_: azure.ai.ml.sweep.Choice
            values:
              - 1
              - 0
          survival_num_hidden_layers:
            _target_: azure.ai.ml.sweep.Choice
            values:
              - 0
              - 1
              - 2
              - 3
          regression_intermediate_size:
            _target_: azure.ai.ml.sweep.Choice
            values:
              - 16
              - 32
              - 64
              - 128
          regression_batch_norm:
            _target_: azure.ai.ml.sweep.Choice
            values:
              - 1
              - 0
          regression_bias:
            _target_: azure.ai.ml.sweep.Choice
            values:
              - 1
              - 0
          regression_num_hidden_layers:
            _target_: azure.ai.ml.sweep.Choice
            values:
              - 0
              - 1
              - 2
              - 3
          regression_loss_weight:
            _target_: azure.ai.ml.sweep.Choice
            values:
              - 0
              - 0.001
              - 0.1
              - 0.2
              - 0.5
              - 0.8
              - 0.9
              - 0.99
              - 0.999
              - 1
        sampling:
          _target_: azure.ai.ml.sweep.BayesianSamplingAlgorithm

        limits:
          max_concurrent_trials: 20
          max_total_trials: 1000
          timeout: 172800
          trial_timeout: 7200

        early_termination:
          _target_: azure.ai.ml.sweep.BanditPolicy
          slack_factor: 0.1
          delay_evaluation: 5
          evaluation_interval: 1
