# @package _global_

do_sweep: true
job: sweep

defaults:
  - override /callbacks: azureml

hydra:
  launcher:
    job:
      params:
        learning_rate: 0.01
        warmup_steps: 40
        weight_decay: 0
        dropout: 0.0
        transformer_hidden_size: 8
        transformer_num_hidden_layers: 2
        transformer_num_attention_heads: 1
        transformer_intermediate_size: 32
        shared_intermediate_size: 64
        shared_num_hidden_layers: 1
        shared_num_labels: 2
        survival_intermediate_size: 64
        survival_num_hidden_layers: 0
      sweep:
        primary_metric: "eval_ipcw_avg"
        goal: "maximize"
        params:
          learning_rate:
            _target_: azure.ai.ml.sweep.Choice
            values:
              - 0.001
              - 0.0001
          warmup_steps:
            _target_: azure.ai.ml.sweep.Choice
            values:
              - 40
              - 80
          weight_decay:
            _target_: azure.ai.ml.sweep.Choice
            values:
              - 0.00001
              - 0.0001
              - 0.001
              - 0
          dropout:
            _target_: azure.ai.ml.sweep.Choice
            values:
              - 0.0
              - 0.1
              - 0.2
          transformer_hidden_size:
            _target_: azure.ai.ml.sweep.Choice
            values:
              - 4
              - 8
              - 16
          transformer_num_attention_heads:
            _target_: azure.ai.ml.sweep.Choice
            values:
              - 2
              - 4
          transformer_intermediate_size:
            _target_: azure.ai.ml.sweep.Choice
            values:
              - 8
              - 16
              - 32
          transformer_num_hidden_layers:
            _target_: azure.ai.ml.sweep.Choice
            values:
              - 2
              - 4
          shared_intermediate_size:
            _target_: azure.ai.ml.sweep.Choice
            values:
              - 4
              - 8
              - 16
              - 32
              - 64
          shared_num_hidden_layers:
            _target_: azure.ai.ml.sweep.Choice
            values:
              - 0
              - 1
          shared_num_labels:
            _target_: azure.ai.ml.sweep.Choice
            values:
              - 4
              - 8
              - 16
          survival_intermediate_size:
            _target_: azure.ai.ml.sweep.Choice
            values:
              - 4
              - 8
              - 16
          survival_num_hidden_layers:
            _target_: azure.ai.ml.sweep.Choice
            values:
              - 0
              - 1
        sampling:
          _target_: azure.ai.ml.sweep.BayesianSamplingAlgorithm

        limits:
          max_concurrent_trials: 100
          max_total_trials: 1000
          timeout: 86400
          trial_timeout: 7200

        early_termination:
          _target_: azure.ai.ml.sweep.BanditPolicy
          slack_factor: 0.1
          delay_evaluation: 10
          evaluation_interval: 1
