training_arguments:
  _target_: transformers.TrainingArguments
  report_to: "tensorboard"
  evaluation_strategy: "steps"
  overwrite_output_dir: True
  num_train_epochs: 300
  per_device_train_batch_size: 512
  per_device_eval_batch_size: 512
  logging_steps: 5
  save_steps: 5
  load_best_model_at_end: True
  greater_is_better: ${tasks.eval_metric_greater_is_better}
  save_strategy: "steps"
  eval_delay: ${warmup_steps}
  eval_steps: 5
  weight_decay: ${weight_decay}
  metric_for_best_model: ${tasks.eval_metric}
  learning_rate: ${learning_rate}
  lr_scheduler_type: cosine
  gradient_accumulation_steps: 4
  warmup_steps: ${warmup_steps}
  save_total_limit: 2
  output_dir: ${modelhub}/${dataset}/${modelname}
  save_safetensors: false
