# @package _global_

do_sweep: true
job: sweep

defaults:
  - override /callbacks: azureml

hydra:
  launcher:
    job:
      params:
        learning_rate: 0.1
        warmup_steps: 40
        weight_decay: 0
        token_emb: 2
        sentence_emb: 1
        dropout: 0.0
        transformer_hidden_size: 8
        transformer_num_hidden_layers: 2
        transformer_num_attention_heads: 1
        transformer_intermediate_size: 32
        shared_intermediate_size: 64
        shared_num_hidden_layers: 1
        shared_num_labels: 2
        survival_intermediate_size: 64
        survival_num_hidden_layers: 0
        ranking_loss_coeff: 0.5
        survival_shared_intermediate_size: 8
        survival_shared_num_hidden_layers: 0
        transformer_layer_norm: false
      sweep:
        primary_metric: "eval_ipcw_avg"
        goal: "maximize"
        params:
          learning_rate:
            _target_: azure.ai.ml.sweep.Choice
            values:
              - 0.01
              - 0.001
          transformer_layer_norm:
            _target_: azure.ai.ml.sweep.Choice
            values:
              - 1
              - 0
          warmup_steps:
            _target_: azure.ai.ml.sweep.Choice
            values:
              - 40
              - 80
          weight_decay:
            _target_: azure.ai.ml.sweep.Choice
            values:
              - 0.1
              - 0.001
              - 0.00001
          token_emb:
            _target_: azure.ai.ml.sweep.Choice
            values:
              - 2
              - 3
              - 4
              - 5
          sentence_emb:
            _target_: azure.ai.ml.sweep.Choice
            values:
              - 1
              - 2
              - 3
          dropout:
            _target_: azure.ai.ml.sweep.Choice
            values:
              - 0.0
              - 0.1
              - 0.2
          transformer_hidden_size:
            _target_: azure.ai.ml.sweep.Choice
            values:
              - 4
              - 8
              - 16
          transformer_num_attention_heads:
            _target_: azure.ai.ml.sweep.Choice
            values:
              - 2
              - 4
          transformer_intermediate_size:
            _target_: azure.ai.ml.sweep.Choice
            values:
              - 16
              - 32
              - 64
          transformer_num_hidden_layers:
            _target_: azure.ai.ml.sweep.Choice
            values:
              - 2
              - 4
          shared_intermediate_size:
            _target_: azure.ai.ml.sweep.Choice
            values:
              - 16
              - 32
              - 64
              - 128
          shared_num_hidden_layers:
            _target_: azure.ai.ml.sweep.Choice
            values:
              - 0
              - 1
          shared_num_labels:
            _target_: azure.ai.ml.sweep.Choice
            values:
              - 8
              - 16
              - 32
          survival_shared_intermediate_size:
            _target_: azure.ai.ml.sweep.Choice
            values:
              - 16
              - 32
              - 64
              - 128
          survival_shared_num_hidden_layers:
            _target_: azure.ai.ml.sweep.Choice
            values:
              - 0
              - 1
          survival_intermediate_size:
            _target_: azure.ai.ml.sweep.Choice
            values:
              - 8
              - 16
              - 32
          survival_num_hidden_layers:
            _target_: azure.ai.ml.sweep.Choice
            values:
              - 0
              - 1
          ranking_loss_coeff:
            _target_: azure.ai.ml.sweep.Choice
            values:
              - 0.1
              - 0.05
              - 0.01
              - 0.005
              - 0.001
        sampling:
          _target_: azure.ai.ml.sweep.BayesianSamplingAlgorithm

        limits:
          max_concurrent_trials: 100
          max_total_trials: 500
          timeout: 172800
          trial_timeout: 7200

        early_termination:
          _target_: azure.ai.ml.sweep.BanditPolicy
          slack_factor: 0.1
          delay_evaluation: 10
          evaluation_interval: 1
