# @package _global_

hydra:
  launcher:
    job:
      inputs:
        - name: HSA_SYNTHETIC
          version: "1"
          path: ${data_source}
          ftype: "uri_file"
          description: "Synthetic dataset originally conceived for the paper hierarchical survival analysis"
          registered: true
          cli: "data_source"
          force: false
