- _target_: sat.evaluate.eval_modules.ComputeBrier
  duration_cuts: ${data.label_transform.save_dir}/duration_cuts.csv
  per_horizon: ${brier_per_horizon}
- _target_: sat.evaluate.eval_modules.ComputeCIndex
  duration_cuts: ${data.label_transform.save_dir}/duration_cuts.csv
- _target_: sat.evaluate.eval_modules.ComputeNLLPHazardLoss
  per_event: ${nllpch_per_event}
