- _target_: sat.evaluate.eval_modules.ComputeOneCalibration
  bins: ${one_calibration_bins}
  num_events: ${data.num_events}
  duration_cuts: ${data.label_transform.save_dir}/duration_cuts.csv
  event_time_thr: ${classification_event_time_thr}
