training_arguments:
  _target_: transformers.TrainingArguments
  report_to: "tensorboard"
  optim: adamw_torch
  overwrite_output_dir: True
  num_train_epochs: 500
  per_device_train_batch_size: 256
  per_device_eval_batch_size: 512
  load_best_model_at_end: True
  greater_is_better: ${tasks.eval_metric_greater_is_better}
  eval_strategy: "steps"
  eval_steps: 1
  logging_strategy: "steps"
  logging_steps: 1
  save_strategy: "steps"
  save_steps: 1
  eval_delay: ${warmup_steps}
  weight_decay: ${weight_decay}
  metric_for_best_model: ${tasks.eval_metric}
  learning_rate: ${learning_rate}
  lr_scheduler_type: cosine
  gradient_accumulation_steps: 1
  warmup_steps: ${warmup_steps}
  save_total_limit: 2
  output_dir: ${modelhub}/${dataset}/${modelname}
  save_safetensors: false
  gradient_checkpointing: false
  dataloader_pin_memory: true
  remove_unused_columns: false
