training_arguments:
  _target_: transformers.TrainingArguments
  report_to: "tensorboard"
  optim: adamw_torch
  overwrite_output_dir: True
  num_train_epochs: 500
  per_device_train_batch_size: 256
  per_device_eval_batch_size: 512
  greater_is_better: ${tasks.eval_metric_greater_is_better}
  load_best_model_at_end: True
  logging_strategy: "no"
  eval_strategy: "epoch"
  eval_steps: 10
  save_strategy: "epoch"
  save_steps: 10
  eval_delay: ${warmup_steps}
  weight_decay: ${weight_decay}
  metric_for_best_model: ${tasks.eval_metric}
  learning_rate: ${learning_rate}
  lr_scheduler_type: cosine
  warmup_steps: ${warmup_steps}
  output_dir: ${modelhub}/${dataset}/${modelname}
  save_safetensors: false
