
# enable color logging
defaults:
  - override hydra_logging: colorlog
  - override job_logging: colorlog

hydra_logging:
  root:
    level: WARN


# output directory, generated dynamically on each run
run:
  dir: ${log_dir}/${task_name}/runs/${now:%Y-%m-%d}_${now:%H-%M-%S}
sweep:
  dir: ${log_dir}/${task_name}/multiruns/${now:%Y-%m-%d}_${now:%H-%M-%S}
  subdir: ${hydra.job.num}

  # use this to also set hydra loggers to 'DEBUG'
  # verbose: True
