sat-transformer:
  _target_: sat.loss.MetaLoss
  losses:
    - _target_: sat.loss.SATNLLPCHazardLoss
      importance_sample_weights: ${data.label_transform.save_dir}/imp_sample.csv
      num_events: ${data.num_events}
  # Fixed weighting by default - balance_strategy defaults to "fixed" if not specified
  coeffs:
    - 1.0
  # Optional: use one of the predefined balancing strategies
  # Uncomment and adjust as needed:
  # balance_strategy: ${losses.balancing.fixed.balance_strategy}
  # balance_params: ${losses.balancing.fixed.balance_params}
sat-transformer-event-duration:
  _target_: sat.loss.L1Loss
  training_set: ${data.label_transform.save_dir}/transformed_train_labels.csv
  importance_sample_weights: ${data.label_transform.save_dir}/imp_sample.csv
  l1_type: margin
  num_events: ${data.num_events}
sat-transformer-event-classification:
  _target_: sat.loss.CrossEntropyLoss
  event_time_thr: ${classification_event_time_thr}
  training_set: ${data.label_transform.save_dir}/transformed_train_labels.csv
  l_type: margin
  importance_sample_weights: ${data.label_transform.save_dir}/imp_sample.csv
  num_events: ${data.num_events}
