sat-transformer:
  _target_: sat.models.tasks.loss.MetaLoss
  losses:
    - _target_: sat.models.tasks.loss.SATNLLPCHazardLoss
      importance_sample_weights: ${data.label_transform.save_dir}/imp_sample.csv
      num_events: ${data.num_events}
  coeffs:
    - 1.0
sat-transformer-event-duration:
  _target_: sat.models.tasks.loss.L1Loss
  training_set: ${data.label_transform.save_dir}/transformed_train_labels.csv
  importance_sample_weights: ${data.label_transform.save_dir}/imp_sample.csv
  l1_type: margin
  num_events: ${data.num_events}
sat-transformer-event-classification:
  _target_: sat.models.tasks.loss.CrossEntropyLoss
  event_time_thr: ${classification_event_time_thr}
  training_set: ${data.label_transform.save_dir}/transformed_train_labels.csv
  l_type: margin
  importance_sample_weights: ${data.label_transform.save_dir}/imp_sample.csv
  num_events: ${data.num_events}
