survival:
    _target_: sat.loss.survival.DSMLoss
    duration_cuts: ${data.label_transform.save_dir}/duration_cuts.csv
    importance_sample_weights: ${data.label_transform.save_dir}/imp_sample.csv
    num_events: ${data.num_events}
    distribution: ${dsm_distribution}
    discount: ${dsm_discount}
    elbo: ${dsm_elbo}
