survival:
  _target_: sat.loss.momentum_buffer.DynamicWeightMoCoLoss
  base_loss:
    _target_: sat.loss.SATNLLPCHazardLoss
    importance_sample_weights: ${data.label_transform.save_dir}/imp_sample.csv
    num_events: ${data.num_events}
  buffer_size: ${moco_buffer_size:2048}
  num_events: ${data.num_events}
  embedding_dim: ${data.label_transform.cuts}
  use_buffer: ${moco_use_buffer:true}
  initial_batch_weight: ${moco_initial_batch_weight:1.0}
  final_batch_weight: ${moco_final_batch_weight:0.5}
  initial_buffer_weight: ${moco_initial_buffer_weight:0.0}
  final_buffer_weight: ${moco_final_buffer_weight:1.0}
  warmup_steps: ${moco_warmup_steps:1000}
  dynamic_buffer: ${moco_dynamic_buffer:true}
  initial_buffer_size: ${moco_initial_buffer_size:128}