survival:
  _target_: sat.loss.momentum_buffer.DynamicWeightMoCoLoss
  base_loss:
    _target_: sat.loss.SATNLLPCHazardLoss
    importance_sample_weights: ${data.label_transform.save_dir}/imp_sample.csv
    num_events: ${data.num_events}
  buffer_size: ${moco_buffer_size}
  num_events: ${data.num_events}
  embedding_dim: ${data.label_transform.cuts}
  use_buffer: ${moco_use_buffer}
  initial_batch_weight: ${moco_initial_batch_weight}
  final_batch_weight: ${moco_final_batch_weight}
  initial_buffer_weight: ${moco_initial_buffer_weight}
  final_buffer_weight: ${moco_final_buffer_weight}
  warmup_steps: ${moco_warmup_steps}
  dynamic_buffer: ${moco_dynamic_buffer}
  initial_buffer_size: ${moco_initial_buffer_size}
