# DeepHit loss components for configuring MetaLoss
defaults:
  - balancing: default

survival:
  _target_: sat.loss.MetaLoss
  losses:
    - _target_: sat.loss.SATNLLPCHazardLoss
      importance_sample_weights: ${data.label_transform.save_dir}/imp_sample.csv
      num_events: ${data.num_events}
    - _target_: sat.loss.SampleRankingLoss
      duration_cuts: ${data.label_transform.save_dir}/duration_cuts.csv
      num_events: ${data.num_events}
      sigma: ${ranking_loss_sigma}  # Scaling factor for ranking loss
      margin: ${ranking_loss_margin}
      importance_sample_weights: ${data.label_transform.save_dir}/imp_sample.csv
    - _target_: sat.loss.IntraEventRankingLoss
      duration_cuts: ${data.label_transform.save_dir}/duration_cuts.csv
      num_events: ${data.num_events}
      sigma: ${ranking_loss_sigma}  # Scaling factor for ranking loss
      importance_sample_weights: ${data.label_transform.save_dir}/imp_sample.csv

  coeffs:
    - ${likelihood_loss_coeff}  # Weight for likelihood loss
    - ${ranking_loss_coeff}  # Weight for ranking loss
    - ${event_ranking_loss_coeff}

  balance_strategy: ${tasks.losses.balancing.balance_strategy}
  balance_params: ${tasks.losses.balancing.balance_params}
