sat-transformer-event-duration:
  _target_: sat.loss.L1Loss
  training_set: ${data.label_transform.save_dir}/transformed_train_labels.csv
  importance_sample_weights: ${data.label_transform.save_dir}/imp_sample.csv
  l1_type: margin
  num_events: ${data.num_events}
