survival:
  _target_: sat.loss.survival.MENSALoss
  duration_cuts: ${data.label_transform.save_dir}/duration_cuts.csv
  importance_sample_weights: ${data.label_transform.save_dir}/imp_sample.csv
  num_events: ${data.num_events}
  distribution: ${mensa_distribution}
  discount: ${mensa_discount}
  elbo: ${mensa_elbo}
  dependency_regularization: ${mensa_dependency_regularization}
