survival:
  _target_: sat.loss.momentum_buffer.MoCoSurvivalLoss
  base_loss:
    _target_: sat.loss.SATNLLPCHazardLoss
    importance_sample_weights: ${data.label_transform.save_dir}/imp_sample.csv
    num_events: ${data.num_events}
  buffer_size: ${moco_buffer_size}
  num_events: ${data.num_events}
  embedding_dim: ${data.label_transform.cuts}
  use_buffer: ${moco_use_buffer}
  current_batch_weight: ${moco_batch_weight}
  buffer_weight: ${moco_buffer_weight}
  dynamic_buffer: ${moco_dynamic_buffer}
  initial_buffer_size: ${moco_initial_buffer_size}
