defaults:
  - balancing: default

survival:
  _target_: sat.loss.MetaLoss
  losses:
    - _target_: sat.loss.SATNLLPCHazardLoss
      importance_sample_weights: ${data.label_transform.save_dir}/imp_sample.csv
      num_events: ${data.num_events}
    - _target_: sat.loss.SampleRankingLoss
      duration_cuts: ${data.label_transform.save_dir}/duration_cuts.csv
      importance_sample_weights: ${data.label_transform.save_dir}/imp_sample.csv
      sigma: ${ranking_loss_sigma}
      num_events: ${data.num_events}
    - _target_: sat.loss.MultiEventRankingLoss
      duration_cuts: ${data.label_transform.save_dir}/duration_cuts.csv
      importance_sample_weights: ${data.label_transform.save_dir}/imp_sample.csv
      sigma: ${event_ranking_loss_sigma}
      num_events: ${data.num_events}
  coeffs:
    - ${likelihood_loss_coeff}
    - ${ranking_loss_coeff}
    - ${event_ranking_loss_coeff}
  balance_strategy: ${tasks.losses.balancing.balance_strategy}
  balance_params: ${tasks.losses.balancing.balance_params}
